version: '3.7'
services:
  frontend:
    image: dubov85/admin-frontend
    depends_on:
      - backend
    networks:
      - app

  backend:
    container_name: admin_api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_DATABASE: admin
      DB_USERNAME: root
      DB_PASSWORD:
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - app

  db:
    container_name: admin_db
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306
    networks:
      - app
networks:
  app:
